server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: center
        uri: lb://center
        predicates:
        - Path=/cc/**
  application:
    name: gateway

  nacos:
    discovery:
      server-addr: 127.0.0.1:8848
      locator:
        enabled: true
        lower-case-service-id: true
        filters:
          - StripPrefix=1






