spring:
  application:
    name: center

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8001


ribbon:
  eager-load:
    clients:  feign，project2
    enabled:  true
feign:
  hystrix:
    enabled: true
